# Generated by Django 3.0 on 2019-12-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('Latitude', models.FloatField(help_text='latitude of sighting')),
                ('Longitude', models.FloatField(help_text='longitude of sighting')),
                ('unique_squirrel_id', models.CharField(help_text='Unique squirrel id.', max_length=32, primary_key=True, serialize=False)),
                ('Shift', models.CharField(choices=[('pm', 'PM'), ('am', 'AM')], default='am', help_text='Sighting session', max_length=2)),
                ('Date', models.DateField(help_text='Sighting date in YYYY-MM-DD format')),
                ('Age', models.CharField(blank=True, choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('', '')], default='adult', help_text='Age of Squirrel', max_length=16, null=True)),
                ('Primary_fur_color', models.CharField(blank=True, choices=[('gray', 'Gray'), ('black', 'Black'), ('cinnamon', 'Cinnamon'), ('', '')], default='gray', help_text='Fur color of Squirrel', max_length=16, null=True)),
                ('Location', models.CharField(blank=True, choices=[('ground_plane', 'Ground_Plane'), ('above_ground', 'Above_Ground'), ('', '')], default='ground_plane', help_text='Location of Squirrel', max_length=20, null=True)),
                ('Specific_location', models.CharField(blank=True, help_text='Specific location of Squirrel', max_length=20, null=True)),
                ('Running', models.BooleanField(default=False)),
                ('Chasing', models.BooleanField(default=False)),
                ('Climbing', models.BooleanField(default=False)),
                ('Eating', models.BooleanField(default=False)),
                ('Foraging', models.BooleanField(default=False)),
                ('Other_activities', models.CharField(blank=True, help_text='Other activity', max_length=20, null=True)),
                ('Kuks', models.BooleanField(default=False)),
                ('Quaas', models.BooleanField(default=False)),
                ('Moans', models.BooleanField(default=False)),
                ('Tail_flags', models.BooleanField(default=False)),
                ('Tail_twitches', models.BooleanField(default=False)),
                ('Approaches', models.BooleanField(default=False)),
                ('Indifferent', models.BooleanField(default=False)),
                ('Runs_from', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Sighting',
        ),
    ]
